// Import styles
import "./styles.css"

// Import all Planks web components
import "@/web-components/plank-button"
import "@/web-components/plank-badge"
import "@/web-components/plank-input"
import "@/web-components/plank-textarea"
import "@/web-components/plank-label"
import "@/web-components/plank-card"
import "@/web-components/plank-separator"
import "@/web-components/plank-skeleton"
import "@/web-components/plank-switch"
import "@/web-components/plank-alert"
import "@/web-components/plank-kbd"
import "@/web-components/plank-progress"
import "@/web-components/plank-aspect-ratio"
import "@/web-components/plank-checkbox"
import "@/web-components/plank-toggle"
import "@/web-components/plank-avatar"
import "@/web-components/plank-collapsible"
import "@/web-components/plank-accordion"
import "@/web-components/plank-tabs"
import "@/web-components/plank-radio-group"
import "@/web-components/plank-toggle-group"
import "@/web-components/plank-slider"
import "@/web-components/plank-tooltip"
import "@/web-components/plank-popover"
import "@/web-components/plank-dialog"
import "@/web-components/plank-alert-dialog"
import "@/web-components/plank-dropdown-menu"
import "@/web-components/plank-context-menu"
